# Use official Nginx image from Docker Hub as a base image
FROM nginx:latest

# Copy your custom configuration file (if any) into the Nginx container
# Example: COPY ./nginx.conf /etc/nginx/nginx.conf

# Expose port 80 to the outside world
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
