name: Build, Lint and Publish Nginx Docker Image

on:
  push

jobs:
  docker-lint-build-push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Lint the code using Super Linter
      - name: Run Super Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Required for Super Linter to post status reports
        continue-on-error: true  # Continue even if linting fails (optional)

      # Step 3: Log in to Docker Hub
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}  # Docker Hub password or token
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USERNAME --password-stdin

      # Step 4: Set up Docker Buildx (necessary for buildx builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Build Docker Image (Nginx)
      - name: Build Docker Image
        run: |
          docker buildx build -t mdasifnasim/nginx_image:latest ./Docker --push
