name: Exploring VAriable and Secrets
on: push
jobs:
    Docker-Publish:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout              
              uses: actions/checkout@v4.1.7
            - name: Super-Linter
              uses: super-linter/super-linter@v7.1.0
            - name: Docker Login
              env:
                #DOCKER_USERNAME: mdasifnasim.
                DOCKER_IMAGE: github-actions-ngnix
                DOCKER_REG: docker.io
              run: echo docker build -t $DOCKER_REG/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE/${{ Secrets.DOCKER_PASS}}:latest

    