name: Build, Lint and Publish Nginx Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  docker-lint-build-push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Lint the code using Super Linter
      - name: Run Super Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.Token_GH }}  # Required for Super Linter to post status reports
        continue-on-error: true  # Continue even if linting fails (optional)

      # Step 3: Log in to Docker Hub
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}  # Docker Hub password or token
        run: |
          echo $DOCKER_PASS | docker login -u $DOCKER_USERNAME --password-stdin

      # Step 4: Build Docker Image (Nginx)
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/github-actions-nginx:latest .

      # Step 5: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push $DOCKER_USERNAME/github-actions-nginx:latest
