name : Ruunig the Script
on: push

jobs:
    acsii-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Running the Scripts
              run: |
                ls -ltra
                chmod +x script.sh
                ./script.sh
    pre-job-test:
        runs-on: ubuntu-latest
        needs: acsii-jobs
        steps:
            - name: Printing the message
              run: |
                hostnamectl
                ifconfig
                uname -r
                sleep 30
    porst-job:
        runs-on: ubuntu-latest
        needs: pre-job-test
        steps:
          - name: End of the Process
            run : |
              python -v
              node -v
              terraform -v
              npm -v

