name : Ruunig the Script
on: push

jobs:
    acsii-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Running the Scripts
              run: |
                ls -ltra
                chmod +x script.sh
                ./script.sh
    pre-job-test:
        runs-on: ubuntu-latest
        steps:
            - name: Printing the message
              run: |
                hostnamectl
                ifconfig
                uname -r
    porst-job:
        runs-on: ubuntu-latest
        steps:
          - name: End of the Process
            run : init 6
            