name: CI_Actions
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Welcome Message
        run: echo "Hello, listing all the files"

      - name: Listing down the files
        run: ls -a

      - name: Viewing the README file
        run: cat README.md
